### ISSUE TITLE
README.md 파일 작성했습니다!

### ISSUE THREAD

**Issue by 22000593lee** [OssTeamProject/Walking_with_puppy#2]
어제 저희 회의한대로 
-mini project 주제
-mini project 에 대한 소개
-image(pixabay 등 무료 이미지 활용)
에 관한 내용 작성했습니다 !!
나머지 내용 작성 부탁드려요 ㅎㅎ

**Comment by chamroro** [comment]
mini project 가 가지고 있는 대략적인 기능 설명

개발환경 및 언어

팀소개 및 팀원이 맡은 역할

업로드 마쳤습니다 수고하셨어요 👏🏻
